name: Release

on:
  push:
    branches:
      - uat

jobs:
  Release:

    runs-on: ubuntu-latest

    env:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"

    steps:
      - uses: actions/checkout@v2

      - name: Determine next version
        uses: gps/determine-next-version@master
        id: next_version
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.next_version.outputs.NEXT_BUILD_VERSION }}
          release_name: v${{ steps.next_version.outputs.NEXT_BUILD_VERSION }}
          draft: false
          prerelease: true
          